### ISSUE TITLE
Which process of Software Development Pair Process aligns with our project?

### ISSUE THREAD

**Issue by bbible3** [CS540-22/TanukiUdon540#14]
Discussed in 2/8/2022 lecture - what is our pair process. Compare to two other options. Is it optimal? If no, is that ok?

**Comment by dseals3** [comment]
Plain old Iterative process aligns best. Scrum and XP are too much, what with Scrum needing 15 minute meetings, a product owner and scrum master in addition to developers and XP being more focused on culture than actual processes. Additionally, the general Iterative process seems to just be the initial creation of the minimum viable product followed by repeated iterations in which more and more features continue to get added. This is exactly what we have talked about even before having read the textbook.
