### ISSUE TITLE
Is it possible to get an actual .gitignore with Unity? If so, let's do it

### ISSUE THREAD

**Issue by bbible3** [CS540-22/TanukiUdon540#15]

**Comment by dseals3** [comment]
It is, I need Bryce to take a look at the new changes in order to get a feel for when we can close this issue.

**Comment by bbible3** [comment]
Unity Collaboration is probably easier than worrying about including the entire Unity directory on the github. We can just manually sync specific (code) files if we decide we want to on GitHub.
