### ISSUE TITLE
Todo: Gather list of snippets to include

### ISSUE THREAD

**Issue by bbible3** [CS540-22/TanukiUdon540#25]
Snippets, links to assets, etc. Probably best to save them into a Json file or something

**Comment by dseals3** [comment]
Done, decided to go with these: https://docs.google.com/spreadsheets/d/e/2PACX-1vTP-eIkYLZh7pDhpO-untxy1zbuoiqdzVP2z5-vg_9ijBW7k8ZC9VP6cVL-ct5yKrySPBPJ6V2ymlWS/pubhtml
