### ISSUE TITLE
Todo: Documentation UI

### ISSUE THREAD

**Issue by bbible3** [CS540-22/TanukiUdon540#29]

**Comment by bbible3** [comment]
I went ahead and assigned this next feature's UI to you so you can progress whenever you'd like. I'll work on the backend and content to some extent. I think a system using TCSV so we can remotely update this as well would be nifty.

**Comment by bbible3** [comment]
@dseals3

**Comment by bbible3** [comment]
@dseals3 Using a similar interface to the assets browser we designed, pulling from a different TSV, generate the UI automatically (switch download button for "link" button, for example)

**Comment by dseals3** [comment]
Documentation UI is now complete and meets requirements, both a new "pop-out" button and uses a different database for the info needed
