### ISSUE TITLE
Todo: Review possibility of PlasticSCM to GitHub via GitSync

### ISSUE THREAD

**Issue by bbible3** [CS540-22/TanukiUdon540#42]
Apparently we can integrate PlasticSCM and GitHub. I haven't looked at this in detail. Give it a look when you get a chance and we'll discuss it, and close this issue after we discuss.

@dseals3 

https://www.plasticscm.com/documentation/gitsync/plastic-scm-version-control-gitsync-guide

**Comment by dseals3** [comment]
Has been reviewed, it appears as though this may be something that @bbible3 has to do since he is the admin

**Comment by bbible3** [comment]
Done! A little tricky, but it works
