### ISSUE TITLE
GitHub detecting HTML

### ISSUE THREAD

**Issue by bbible3** [CS540-22/TanukiUdon540#45]
This seems to be associated with Linguist. https://github.com/github/linguist/blob/b3664e4f242c842e356bd011090f85514d147948/lib/linguist/languages.yml#L2060-L2068
(Search for "HTML")
-- We can probably exclude, or rather, include only desired code, in the Linguist analysis.

**Comment by bbible3** [comment]
https://stackoverflow.com/questions/29932342/is-there-a-way-to-ignore-calculating-language-statistics-for-a-directory-on-gith

**Comment by dseals3** [comment]
I believe this has been fixed with the new gitignore changes so I'll be closing this issue
