### ISSUE TITLE
Clean up synced directories on PlasticSCM's GitSync

### ISSUE THREAD

**Issue by bbible3** [CS540-22/TanukiUdon540#46]

**Comment by dseals3** [comment]
@bbible3 With your permission, this can be closed. Only things needed now is to 1. make sure that when you do another sync with Plastic that our .gitignore will actually ignore the Assets/CyanEmu and Assets/Udon folders and 2. Let me know if there are any other folders that I need to get rid of

**Comment by bbible3** [comment]
Thank you! We can test it with the next push.

I would reckon we should also add the following directories:

Assets/Gizmos, Assets/Scenes, Assets/VRChat Examples, /Packages

@dseals3

**Comment by dseals3** [comment]
@bbible3 Done! Gonna close this issue
