### ISSUE TITLE
Prototype UI

### ISSUE THREAD

**Issue by bbible3** [CS540-22/TanukiUdon540#7]

**Comment by bbible3** [comment]
Block out rough UI with dropdown categories (or tabs, or whatever you think looks good) for planned upcoming features (code snippet library, code search, tutorials, features, etc)

**Comment by bbible3** [comment]
Also, clean up existing UI - if you want to make it look pretty or do something else with the visuals (maybe add a logo?)

**Comment by dseals3** [comment]
Logo added, Header added, a semblance of a grouping style has been added, and the features implemented work! I think we have a good framework to go off of for our UI now. Completed!
